version: "3.8"
volumes:
  db-store-hoge:
  # php-fpm-socket:
  php-practice-hoge:
  pma-hoge:
services:
  app:
    build: ./docker/php
    volumes:
      - php-practice-hoge:/var/run/php-fpm
      - ../backend:/work/backend
      - ./docker/php/bash/.bash_history:/root/.bash_history
      - ./docker/php/bash/psysh:/root/.config/psysh

  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - php-practice-hoge:/var/run/php-fpm
      - ../backend:/work/backend

  db:
    build: ./docker/mysql
    volumes:
      - db-store-hoge:/var/lib/mysql
    ports:
      - 3306:3306
  
  phpmyadmin:
    build: ./docker/phpMyAdmin
    ports:
      - 8888:80
    volumes:
      - pma-hoge:/sessions