version: "3.8"
volumes:
  dbpg-store-hoge:
  # php-fpm-socket:
  php-practice-hogepg:

services:
  app:
    build: ./docker/php
    volumes:
      - php-practice-hogepg:/var/run/php-fpm
      - ../backend:/work/backend
      - ./docker/php/bash/.bash_history:/root/.bash_history
      - ./docker/php/bash/psysh:/root/.config/psysh

  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - php-practice-hogepg:/var/run/php-fpm
      - ../backend:/work/backend

  db:
    build: ./docker/pg
    volumes:
      - dbpg-store-hoge:/var/lib/postgresql/data
    ports:
      - 5432:5432
